name: flutter_webview_bridge
description: "A new Flutter WebView Bridge package project."
version: 0.0.1
homepage: https://github.com/JosephNK/flutter_webview_bridge

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2
  flutter_timezone: ^4.1.1
  permission_handler: ^12.0.1
  android_id: ^0.4.0

  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.8.2
  webview_flutter_wkwebview: ^3.22.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
